#!/usr/bin/env bash

echo
echo -e "     Black \e[0;40m    \e[0m\e[0;100m    \e[0m Dark Grey"
echo -e "       Red \e[0;41m    \e[0m\e[0;101m    \e[0m Light Red"
echo -e "     Green \e[0;42m    \e[0m\e[0;102m    \e[0m Light Green"
echo -e "    Yellow \e[0;43m    \e[0m\e[0;103m    \e[0m Light Yellow"
echo -e "      Blue \e[0;44m    \e[0m\e[0;104m    \e[0m Light Blue"
echo -e "   Magenta \e[0;45m    \e[0m\e[0;105m    \e[0m Light Magenta"
echo -e "      Cyan \e[0;46m    \e[0m\e[0;106m    \e[0m Light Cyan"
echo -e "Light Grey \e[0;47m    \e[0m\e[0;107m    \e[0m White"
echo
