#!/usr/bin/env bash

which ctags > /dev/null 2>&1
CTAGS=$?
if [[ $CTAGS == 0 ]]; then # do we have ctags installed?

    ctags --version 2> /dev/null | grep -i exuberant > /dev/null 2>&1
    EXUBERANT=$?
    if [[ $EXUBERANT == 0 ]]; then # is it Exuberant Ctags?

        echo -n "generating ctags..."
        set -e
        PATH="/usr/local/bin:$PATH"
        trap "rm -f .git/tags.$$" EXIT

        ctags --tag-relative -R -f .git/tags.$$ --exclude=.git --languages=-sql,javascript
        mv .git/tags.$$ .git/tags
        echo "DONE"

    fi

fi
